version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - app-logs:/app/logs
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

volumes:
  app-logs:

networks:
  app-network: